### ISSUE TITLE
Jira Subtickets are not added as Subtaks in Omnifocus

### ISSUE THREAD

**Issue by Bastian-Kuhn** [Bastian-Kuhn/jira-omnifocus#2]
Subtask should be also a Subticket, instead they are added as Toplevel Task

**Comment by snwfdhmp** [comment]
@Bastian-Kuhn did you add this feature ?

**Comment by Bastian-Kuhn** [comment]
@snwfdhmp yes, did so long ago just forgot to close this.

**Comment by snwfdhmp** [comment]
@Bastian-Kuhn  haha great ! I don't use subtasks very much myself but thats a nice feature

**Comment by Bastian-Kuhn** [comment]
Dammit, now when you say it out loud, in confused subtasks from jira with comments which are subtasks in OmniFocus :( 
So, this is still open...

**Comment by snwfdhmp** [comment]
@Bastian-Kuhn i'm not sure i understand what you mean

**Comment by Bastian-Kuhn** [comment]
I fixed the feature which adds the Jira Ticket Comments as a Subtask into OmniFocus. But this Issue was about adding Jira Sub Tickets as a Subtask into OmniFocus, and I confused that. Currently, Sub Tickets are added like normal Tickets into OmniFocus

**Comment by snwfdhmp** [comment]
Oh I see
